name: test-controlled-daemons
base: core18
version: '0.1'
summary: test a controlled daemon
description: a controlled daemon
  

grade: devel
confinement: strict

apps:
  controlled-1:
    command: bin/controlled-1
    daemon: simple
  start-controlled-1:
    command: bin/start-controlled-1
  stop-controlled-1:
    command: bin/stop-controlled-1

parts:
  controlled-1:
    source: controlled-1
    plugin: dump
  start-controlled-1:
    source: start-controlled-1
    plugin: dump
  stop-controlled-1:
    source: stop-controlled-1
    plugin: dump
